config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks
  devise_for :users
  root "welcome#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "my_portfolio", to: "users#my_portfolio"
  get "search_stock", to: "stocks#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
    ticker = ticker_symbol.downcase
    
    client =
      IEX::Api::Client.new(
        publishable_token: Rails.application.credentials.iex[:sandbox_api_key],
        endpoint: 'https://sandbox.iexapis.com/v1'
      )

    begin
      new(
        ticker: ticker,
        name: client.company(ticker).company_name,
        last_price: client.price(ticker)
      )
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker)
    where(ticker: ticker).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker)
    stock = Stock.check_db(ticker)
    return false unless stock

    stocks.where(id: stock.id).exists?
  end

  def can_track_stocks?(ticker)
    under_stock_limit? && !stock_already_tracked?(ticker)
  end

  def full_name
    return 'Anonymous' unless first_name || last_name

    "#{first_name} #{last_name}"
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if (params[:stock].present?)
      @stock = Stock.new_lookup(params[:stock])
      if (@stock)
        respond_to do |format| 
          format.js { render partial: 'users/result' } 
        end
      else
        respond_to do |format|
          flash.now[:alert] = 'Please enter a valid symbol to search'
          format.js { render partial: 'users/result' } 
        end
      end
    else
      respond_to do |format|
          
        flash.now[:alert] = 'Please enter a symbol to search'
        format.js { render partial: 'users/result' } 
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @stocks = current_user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
  <div class='alert alert-danger'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
	<%= alert %>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
 <% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Finacial Tracker", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Portfolio", my_portfolio_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= "#{current_user.full_name}" %>
          </li>
     
          <li class="nav-item">
            
              <%= link_to "Sign Out",   destroy_user_session_path, method: :delete %>
            
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StocksTrackingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_result.html.erb
<%= render 'layouts/messages' %>

<% if @stock %>
  <div class="card card-header">
    <strong>Ticker: </strong><%= @stock.ticker %>
    <strong>Name: </strong><%= @stock.name %>
    <strong>Last Price: </strong><%= @stock.last_price %>
    <% if current_user.can_track_stocks?(@stock.ticker) %>
      <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success", method: "POST" %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector("#result").innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/my_portfolio.html.erb
<h3>Search Stocks</h3>
<%= form_tag search_stock_path, method: :get, remote: true do %>
  <div class="form-group row">
    <div class="col-sm-9">
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg"%>
    </div>
    <div class="col-sm-3">
      <%= button_tag type: "submit", class: "btn btn-success" do %>
        <%= 'Search' %>
      <% end %>
    </div>
  </div>
<% end  %>
<div id="result">
</div>
<% if !@stocks.empty? %>
  <div class="row">
    <div class="col-9">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Last Price</th>
          </tr>
        </thead>
        <tbody>
          <% @stocks.each_with_index do |stock, i| %>
            <tr>
              <th scope="row"><%= i + 1 %></th>
              <td><%= stock.ticker %></td>
              <td><%= stock.name %></td>
              <td><%= stock.last_price %></td>
              <td><%= link_to "Remove", user_stock_path(stock), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-warning" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<button>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
</button>